name: Fx.MorphElement
author: vincentbluff
category: Effects
tags: [effects, morph]
current: 1.0.3
docs: http://github.com/vincentbluff/Fx.MorphElement/blob/master/README.md
demo: http://vincentbluff.github.com/Fx.MorphElement